branch-defaults:
  default:
    environment: svl-ml-api-env
    group_suffix: null
global:
  application_name: svl-ml-api
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.6
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
